#!/bin/bash
# Transdroid Setup
scriptversion="1.0.0"
scriptname="transdroid.setup"
# adamaze, konichiwa
#
# wget -qO ~/transdroid.setup https://raw.githubusercontent.com/frankthetank7254/feral/master/transdroid-setup && bash ~/transdroid.setup
#
############################
## Version History Starts ##
############################
#
# How do I customise this updater? 
# 1: scriptversion="0.0.0" replace "0.0.0" with your script version. This will be shown to the user at the current version.
# 2: scriptname="somescript" replace "somescript" with your script name. Make it unique to this script.
# 3: Set the scripturl variable in the variable section to the RAW github URl of the script for updating.
# 4: Insert your script in the "Script goes here" labelled section
#
# This updater deals with updating a single file, the "~/bin/somescript", by updating and switching to this script.
#
# http://grover.open2space.com/content/bash-script-menus-and-functions
#
############################
### Version History Ends ###
############################
option1="ruTorrent"
option2="Deluge"
option3="Transmission"
option4="Quit"
############################
###### Variable Start ######
############################
#
scripturl="https://raw.githubusercontent.com/frankthetank7254/feral/master/transdroid-setup"
#
############################
####### Variable End #######
############################
#
############################
#### Self Updater Start ####
############################
#
[[ ! -d ~/bin ]] && mkdir -p ~/bin
[[ ! -f ~/bin/"$scriptname" ]] && wget -qO ~/bin/"$scriptname" "$scripturl"
#
wget -qO ~/.000"$scriptname" "$scripturl"
#
if [[ $(sha256sum ~/.000"$scriptname" | awk '{print $1}') != $(sha256sum ~/bin/"$scriptname" | awk '{print $1}') ]]
then
    echo -e "#!/bin/bash\nwget -qO ~/bin/$scriptname $scripturl\ncd && rm -f $scriptname{.sh,}\nbash ~/bin/$scriptname\nexit" > ~/.111"$scriptname"
    bash ~/.111"$scriptname"
    exit
else
    if [[ -z $(ps x | fgrep "bash $HOME/bin/$scriptname" | grep -v grep | head -n 1 | awk '{print $1}') && $(ps x | fgrep "bash $HOME/bin/$scriptname" | grep -v grep | head -n 1 | awk '{print $1}') -ne "$$" ]]
    then
        echo -e "#!/bin/bash\ncd && rm -f $scriptname{.sh,}\nbash ~/bin/$scriptname\nexit" > ~/.222"$scriptname"
        bash ~/.222"$scriptname"
        exit
    fi
fi
cd && rm -f .{000,111,222}"$scriptname"
chmod -f 700 ~/bin/"$scriptname"
#
############################
##### Self Updater End #####
############################
#
############################
#### Core Script Starts ####
############################
#
echo
echo -e "Hello $(whoami), you have the latest version of the" "\033[36m""$scriptname""\e[0m" "script. This script version is:" "\033[31m""$scriptversion""\e[0m"
echo
read -ep "The scripts have been updated, do you wish to continue [y] or exit now [q] : " -i "y" updatestatus
echo
if [[ "$updatestatus" =~ ^[Yy]$ ]]
then
#
############################
#### User Script Starts ####
############################
#
	echo This script will generate the "settings.json" file that Transdroid requires for importing settings. Please choose the client you are using.
    showMenu () 
    {
            echo "1) $option1"
            echo "2) $option2"
            echo "3) $option3"
            echo "4) $option4"
			echo
    }

    while [ 1 ]
    do
            showMenu
            read -e CHOICE
            echo
            case "$CHOICE" in
                    "1")
							tmpdir=tmp$(shuf -i 10000-90000 -n 1)
							mkdir $tmpdir
							wget -qO ~/$tmpdir/rtorrent-settings.json https://raw.githubusercontent.com/frankthetank7254/feral/master/rtorrent-settings.json
							
							echo  "Please enter the ruTorrent password from your Account overview page:"
							read rtpass
							
							sed "s/USERNAME-CHANGEME/$(whoami)/" ~/$tmpdir/rtorrent-settings.json > ~/$tmpdir/rtorrent-settings.json.1
							sed "s/HOSTNAME-CHANGEME/$(hostname -f)/" ~/$tmpdir/rtorrent-settings.json.1 > ~/$tmpdir/rtorrent-settings.json.2
							sed "s/RTORRENTPASSWORD-CHANGEME/$rtpass/" ~/$tmpdir/rtorrent-settings.json.2 > ~/$tmpdir/rtorrent-settings.json.3
							sed "s/SERVERNAME-CHANGEME/$(hostname)-rutorrent/" ~/$tmpdir/rtorrent-settings.json.3 > ~/$tmpdir/rtorrent-settings.json
							cp -r ~/$tmpdir ~/www/$(whoami).$(hostname)/public_html/
							
							URL="http://$(whoami).$(hostname -f)/$tmpdir/rtorrent-settings.json"
							echo Download the generated config file to your phone using the following link, then, in Transdroid, go to Settings>>System>>Import Settings, and select the downloaded file.
							echo Use your phone to navigate here: $URL
							echo or use the qrcode below:
							echo
							#qrencode -t ASCII -o ~/$tmpdir/ascii-code.txt $URL
							#sed 's/ /M/g' ~/$tmpdir/ascii-code.txt > ~/$tmpdir/ascii-code2.txt
							#sed 's/#/ /g' ~/$tmpdir/ascii-code2.txt
							
							echo After you have downloaded the config file, press ENTER to clean up.
							read useless
							rm -r ~/$tmpdir ~/www/$(whoami).$(hostname)/public_html/$tmpdir/
                            echo
                            ;;
                    "2")
							tmpdir=tmp$(shuf -i 10000-90000 -n 1)
							mkdir $tmpdir
							wget -qO ~/$tmpdir/deluge-settings.json https://raw.githubusercontent.com/frankthetank7254/feral/master/deluge-settings.json
							
							echo  "Please enter the ruTorrent password from your Account overview page:"
							read rtpass
							
							sed "s/USERNAME-CHANGEME/$(whoami)/" ~/$tmpdir/deluge-settings.json > ~/$tmpdir/deluge-settings.json.1
							sed "s/HOSTNAME-CHANGEME/$(hostname -f)/" ~/$tmpdir/deluge-settings.json.1 > ~/$tmpdir/deluge-settings.json.2
							sed "s/RTORRENTPASSWORD-CHANGEME/$rtpass/" ~/$tmpdir/deluge-settings.json.2 > ~/$tmpdir/deluge-settings.json.3
							sed "s/SERVERNAME-CHANGEME/$(hostname)-rutorrent/" ~/$tmpdir/deluge-settings.json.3 > ~/$tmpdir/deluge-settings.json
							cp -r ~/$tmpdir ~/www/$(whoami).$(hostname)/public_html/
							
							URL="http://$(whoami).$(hostname -f)/$tmpdir/deluge-settings.json"
							echo Download the generated config file to your phone using the following link, then, in Transdroid, go to Settings>>System>>Import Settings, and select the downloaded file.
							echo Use your phone to navigate here: $URL
							echo or use the qrcode below:
							echo
							#qrencode -t ASCII -o ~/$tmpdir/ascii-code.txt $URL
							#sed 's/ /M/g' ~/$tmpdir/ascii-code.txt > ~/$tmpdir/ascii-code2.txt
							#sed 's/#/ /g' ~/$tmpdir/ascii-code2.txt
							
							echo After you have downloaded the config file, press ENTER to clean up.
							read useless
							rm -r ~/$tmpdir ~/www/$(whoami).$(hostname)/public_html/$tmpdir/
                            echo
                            ;;
                    "3")
							tmpdir=tmp$(shuf -i 10000-90000 -n 1)
							mkdir $tmpdir
							wget -qO ~/$tmpdir/transmission-settings.json https://raw.githubusercontent.com/frankthetank7254/feral/master/transmission-settings.json
							
							echo  "Please enter the ruTorrent password from your Account overview page:"
							read rtpass
							
							sed "s/USERNAME-CHANGEME/$(whoami)/" ~/$tmpdir/transmission-settings.json > ~/$tmpdir/transmission-settings.json.1
							sed "s/HOSTNAME-CHANGEME/$(hostname -f)/" ~/$tmpdir/transmission-settings.json.1 > ~/$tmpdir/transmission-settings.json.2
							sed "s/RTORRENTPASSWORD-CHANGEME/$rtpass/" ~/$tmpdir/transmission-settings.json.2 > ~/$tmpdir/transmission-settings.json.3
							sed "s/SERVERNAME-CHANGEME/$(hostname)-rutorrent/" ~/$tmpdir/transmission-settings.json.3 > ~/$tmpdir/transmission-settings.json
							cp -r ~/$tmpdir ~/www/$(whoami).$(hostname)/public_html/
							
							URL="http://$(whoami).$(hostname -f)/$tmpdir/transmission-settings.json"
							echo Download the generated config file to your phone using the following link, then, in Transdroid, go to Settings>>System>>Import Settings, and select the downloaded file.
							echo Use your phone to navigate here: $URL
							echo or use the qrcode below:
							echo
							#qrencode -t ASCII -o ~/$tmpdir/ascii-code.txt $URL
							#sed 's/ /M/g' ~/$tmpdir/ascii-code.txt > ~/$tmpdir/ascii-code2.txt
							#sed 's/#/ /g' ~/$tmpdir/ascii-code2.txt
							
							echo After you have downloaded the config file, press ENTER to clean up.
							read useless
							rm -r ~/$tmpdir ~/www/$(whoami).$(hostname)/public_html/$tmpdir/
                            echo
                            ;;
					"4")
                            echo "You chose to quit the script."
                            echo
                            exit
                            ;;
            esac
    done
#
############################
##### User Script End  #####
############################
#
else
    echo -e "You chose to exit after updating the scripts."
    echo
    cd && bash
    exit 1
fi
#
############################
##### Core Script Ends #####
############################
#