#!/bin/bash
# Transdroid Setup
scriptversion="1.0.1"
scriptname="transdroid.setup"
# adamaze, konichiwa
#
# wget -qO ~/transdroid.setup http://git.io/pKBcwg && bash ~/transdroid.setup
#
############################
## Version History Starts ##
############################
#
# How do I customise this updater? 
# 1: scriptversion="0.0.0" replace "0.0.0" with your script version. This will be shown to the user at the current version.
# 2: scriptname="somescript" replace "somescript" with your script name. Make it unique to this script.
# 3: Set the scripturl variable in the variable section to the RAW github URl of the script for updating.
# 4: Insert your script in the "Script goes here" labelled section
#
# This updater deals with updating a single file, the "~/bin/somescript", by updating and switching to this script.
#
# http://grover.open2space.com/content/bash-script-menus-and-functions
#
############################
### Version History Ends ###
############################
#
############################
###### Variable Start ######
############################
#
scripturl="https://raw.githubusercontent.com/frankthetank7254/feral/master/transdroid-setup"
#
rtorrentjson="https://raw.githubusercontent.com/frankthetank7254/feral/master/rtorrent-settings.json"
delugejson="https://raw.githubusercontent.com/frankthetank7254/feral/master/deluge-settings.json"
transmissionjson="https://raw.githubusercontent.com/frankthetank7254/feral/master/transmission-settings.json"
#
option1="ruTorrent"
option2="Deluge"
option3="Transmission"
option4="Quit"
#
tmpdir1=".transdroid_import"
tmpdir2="transdroid_import"
#
# Random password generation
randompass=$(< /dev/urandom tr -dc '1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz' | head -c20; echo;)
#
URL="https://$(whoami):$randompass@$(hostname -f)/$(whoami)/$tmpdir2/"
#
############################
####### Variable End #######
############################
#
############################
#### Self Updater Start ####
############################
#
[[ ! -d ~/bin ]] && mkdir -p ~/bin
[[ ! -f ~/bin/"$scriptname" ]] && wget -qO ~/bin/"$scriptname" "$scripturl"
#
wget -qO ~/.000"$scriptname" "$scripturl"
#
if [[ $(sha256sum ~/.000"$scriptname" | awk '{print $1}') != $(sha256sum ~/bin/"$scriptname" | awk '{print $1}') ]]
then
    echo -e "#!/bin/bash\nwget -qO ~/bin/$scriptname $scripturl\ncd && rm -f $scriptname{.sh,}\nbash ~/bin/$scriptname\nexit" > ~/.111"$scriptname"
    bash ~/.111"$scriptname"
    exit
else
    if [[ -z $(ps x | fgrep "bash $HOME/bin/$scriptname" | grep -v grep | head -n 1 | awk '{print $1}') && $(ps x | fgrep "bash $HOME/bin/$scriptname" | grep -v grep | head -n 1 | awk '{print $1}') -ne "$$" ]]
    then
        echo -e "#!/bin/bash\ncd && rm -f $scriptname{.sh,}\nbash ~/bin/$scriptname\nexit" > ~/.222"$scriptname"
        bash ~/.222"$scriptname"
        exit
    fi
fi
cd && rm -f .{000,111,222}"$scriptname"
chmod -f 700 ~/bin/"$scriptname"
#
############################
##### Self Updater End #####
############################
#
############################
#### Core Script Starts ####
############################
#
echo
echo -e "Hello $(whoami), you have the latest version of the" "\033[36m""$scriptname""\e[0m" "script. This script version is:" "\033[31m""$scriptversion""\e[0m"
echo
read -ep "The scripts have been updated, do you wish to continue [y] or exit now [q] : " -i "y" updatestatus
echo
if [[ "$updatestatus" =~ ^[Yy]$ ]]
then
#
############################
#### User Script Starts ####
############################
#
    echo This script will generate the "settings.json" file that Transdroid requires for importing settings. Please choose the client you are using.
    echo
    showMenu () 
    {
            echo "1) $option1"
            echo "2) $option2"
            echo "3) $option3"
            echo "4) $option4"
            echo
    }

    while [ 1 ]
    do
            showMenu
            read -e CHOICE
            echo
            case "$CHOICE" in
                    "1")
                            mkdir -p ~/$tmpdir1
                            #
                            wget -qO ~/$tmpdir1/qrencode_3.3.0-2_amd64.deb http://ftp.uk.debian.org/debian/pool/main/q/qrencode/qrencode_3.3.0-2_amd64.deb
                            wget -qO ~/$tmpdir1/libqrencode3_3.3.0-2_amd64.deb http://ftp.uk.debian.org/debian/pool/main/q/qrencode/libqrencode3_3.3.0-2_amd64.deb
                            #
                            dpkg-deb -x ~/$tmpdir1/qrencode_3.3.0-2_amd64.deb ~/$tmpdir1
                            dpkg-deb -x ~/$tmpdir1/libqrencode3_3.3.0-2_amd64.deb ~/$tmpdir1
                            #
                            wget -qO ~/$tmpdir1/settings.json "$rtorrentjson"
                            read -ep "Please enter the ruTorrent password from your Account overview page: " pass
                            echo
                            #
                            sed -i 's/USERNAME-CHANGEME/'$(whoami)'/' ~/$tmpdir1/settings.json
                            sed -i 's/HOSTNAME_CHANGEME/'$(hostname -f)'/' ~/$tmpdir1/settings.json
                            sed -i 's/PASSWORD-CHANGEME/'$pass'/' ~/$tmpdir1/settings.json
                            #
                            mkdir -p ~/www/$(whoami).$(hostname)/public_html/$tmpdir2
                            #
                            cp -f ~/$tmpdir1/settings.json ~/www/$(whoami).$(hostname)/public_html/$tmpdir2/settings.json
                            htpasswd -cbm ~/www/$(whoami).$(hostname -f)/public_html/$tmpdir2/.htpasswd "$(whoami)" "$randompass" > /dev/null 2>&1
                            #
                            if [[ -d ~/.nginx/conf.d/000-default-server.d ]]
                            then
                                echo -e 'location /'"$tmpdir2"' {\n    auth_basic "'"$tmpdir2"'";\n    auth_basic_user_file "'"$HOME"'/www/'$(whoami)'.'$(hostname -f)'/public_html/'"$tmpdir2"'/.htpasswd";\n}' > ~/.nginx/conf.d/000-default-server.d/transdroid_import.conf
                                /usr/sbin/nginx -s reload -c ~/.nginx/nginx.conf > /dev/null 2>&1
                            fi
                            #
                            echo -e 'AuthType Basic\nAuthName "'"$tmpdir2"'"\nAuthUserFile "'"$HOME"'/www/'$(whoami)'.'$(hostname -f)'/public_html/'"$tmpdir2"'/.htpasswd"\nRequire "'$(whoami)'"' > ~/www/$(whoami).$(hostname -f)/public_html/"$tmpdir2"/.htaccess
                            #
                            LD_LIBRARY_PATH=~/.transdroid_import/usr/lib/x86_64-linux-gnu ~/.transdroid_import/usr/bin/qrencode -m 1 -t ANSI256 -o - "$URL"
                            #
                            echo
                            echo -e "\033[33m""Use the QRCode for quick access to the generated settings.json""\e[0m"
                            echo
                            echo "1: Download the generated config file to your phone using the following link"
                            echo
                            echo -e "\033[32m""$URL""\e[0m"
                            echo
                            echo -e "2: Open Transdroid/Transdrone and Go to:" "\033[36m""Settings > System > Export settings""\e[0ms so that the appropriate folder is created."
                            echo
                            echo -e "3: Open Transdroid/Transdrone and Go to:" "\033[36m""Settings > System > Import settings""\e[0m"
                            echo
                            echo "4: You will be told which directory the file is required to be in for import. Copy it there then import it."
                            echo
                            read -ep "After you have downloaded the config file, press ENTER to clean up." useless
                            echo
                            #
                            if [[ ! -z "$tmpdir1" && ! -z "$tmpdir2" ]]
                            then
                                cd && rm -rf $tmpdir1 ~/www/$(whoami).$(hostname)/public_html/$tmpdir2
                                if [[ -d ~/.nginx/conf.d/000-default-server.d ]]
                                then
                                    rm -f ~/.nginx/conf.d/000-default-server.d/transdroid_import.conf
                                    /usr/sbin/nginx -s reload -c ~/.nginx/nginx.conf > /dev/null 2>&1
                                fi
                            else
                                echo "Nothing was removed. Please check manually."
                            fi
                            ;;
                    "2")
                            mkdir -p ~/$tmpdir1
                            #
                            wget -qO ~/$tmpdir1/qrencode_3.3.0-2_amd64.deb http://ftp.uk.debian.org/debian/pool/main/q/qrencode/qrencode_3.3.0-2_amd64.deb
                            wget -qO ~/$tmpdir1/libqrencode3_3.3.0-2_amd64.deb http://ftp.uk.debian.org/debian/pool/main/q/qrencode/libqrencode3_3.3.0-2_amd64.deb
                            #
                            dpkg-deb -x ~/$tmpdir1/qrencode_3.3.0-2_amd64.deb ~/$tmpdir1
                            dpkg-deb -x ~/$tmpdir1/libqrencode3_3.3.0-2_amd64.deb ~/$tmpdir1
                            #
                            wget -qO ~/$tmpdir1/settings.json "$delugejson"
                            read -ep "Please enter the Deluge password from your Account overview page: " pass
                            echo
                            #
                            sed -i 's/USERNAME-CHANGEME/'$(whoami)'/g' ~/$tmpdir1/settings.json
                            sed -i 's/HOSTNAME_CHANGEME/'$(hostname -f)'/' ~/$tmpdir1/settings.json
                            sed -i 's/PASSWORD-CHANGEME/'$pass'/' ~/$tmpdir1/settings.json
                            #
                            mkdir -p ~/www/$(whoami).$(hostname)/public_html/$tmpdir2
                            #
                            cp -f ~/$tmpdir1/settings.json ~/www/$(whoami).$(hostname)/public_html/$tmpdir2/settings.json
                            htpasswd -cbm ~/www/$(whoami).$(hostname -f)/public_html/$tmpdir2/.htpasswd "$(whoami)" "$randompass" > /dev/null 2>&1
                            #
                            if [[ -d ~/.nginx/conf.d/000-default-server.d ]]
                            then
                                echo -e 'location /'"$tmpdir2"' {\n    auth_basic "'"$tmpdir2"'";\n    auth_basic_user_file "'"$HOME"'/www/'$(whoami)'.'$(hostname -f)'/public_html/'"$tmpdir2"'/.htpasswd";\n}' > ~/.nginx/conf.d/000-default-server.d/transdroid_import.conf
                                /usr/sbin/nginx -s reload -c ~/.nginx/nginx.conf > /dev/null 2>&1
                            fi
                            #
                            echo -e 'AuthType Basic\nAuthName "'"$tmpdir2"'"\nAuthUserFile "'"$HOME"'/www/'$(whoami)'.'$(hostname -f)'/public_html/'"$tmpdir2"'/.htpasswd"\nRequire "'$(whoami)'"' > ~/www/$(whoami).$(hostname -f)/public_html/"$tmpdir2"/.htaccess
                            #
                            LD_LIBRARY_PATH=~/.transdroid_import/usr/lib/x86_64-linux-gnu ~/.transdroid_import/usr/bin/qrencode -m 1 -t ANSI256 -o - "$URL"
                            #
                            echo
                            echo -e "\033[33m""Use the QRCode for quick access to the generated settings.json""\e[0m"
                            echo
                            echo "1: Download the generated config file to your phone using the following link"
                            echo
                            echo -e "\033[32m""$URL""\e[0m"
                            echo
                            echo -e "2: Open Transdroid/Transdrone and Go to:" "\033[36m""Settings > System > Export settings""\e[0ms so that the appropriate folder is created."
                            echo
                            echo -e "3: Open Transdroid/Transdrone and Go to:" "\033[36m""Settings > System > Import settings""\e[0m"
                            echo
                            echo "4: You will be told which directory the file is required to be in for import. Copy it there then import it."
                            echo
                            read -ep "After you have downloaded the config file, press ENTER to clean up." useless
                            echo
                            #
                            if [[ ! -z "$tmpdir1" && ! -z "$tmpdir2" ]]
                            then
                                cd && rm -rf $tmpdir1 ~/www/$(whoami).$(hostname)/public_html/$tmpdir2
                                if [[ -d ~/.nginx/conf.d/000-default-server.d ]]
                                then
                                    rm -f ~/.nginx/conf.d/000-default-server.d/transdroid_import.conf
                                    /usr/sbin/nginx -s reload -c ~/.nginx/nginx.conf > /dev/null 2>&1
                                fi
                            else
                                echo "Nothing was removed. Please check manually."
                            fi
                            ;;
                    "3")
                            mkdir -p ~/$tmpdir1
                            #
                            wget -qO ~/$tmpdir1/qrencode_3.3.0-2_amd64.deb http://ftp.uk.debian.org/debian/pool/main/q/qrencode/qrencode_3.3.0-2_amd64.deb
                            wget -qO ~/$tmpdir1/libqrencode3_3.3.0-2_amd64.deb http://ftp.uk.debian.org/debian/pool/main/q/qrencode/libqrencode3_3.3.0-2_amd64.deb
                            #
                            dpkg-deb -x ~/$tmpdir1/qrencode_3.3.0-2_amd64.deb ~/$tmpdir1
                            dpkg-deb -x ~/$tmpdir1/libqrencode3_3.3.0-2_amd64.deb ~/$tmpdir1
                            #
                            wget -qO ~/$tmpdir1/settings.json "$transmissionjson"
                            read -ep "Please enter the Transmission password from your Account overview page: " pass
                            echo
                            #
                            sed -i 's/USERNAME-CHANGEME/'$(whoami)'/' ~/$tmpdir1/settings.json
                            sed -i 's/HOSTNAME_CHANGEME/'$(hostname -f)'/' ~/$tmpdir1/settings.json
                            sed -i 's/PASSWORD-CHANGEME/'$pass'/' ~/$tmpdir1/settings.json
                            #
                            mkdir -p ~/www/$(whoami).$(hostname)/public_html/$tmpdir2
                            #
                            cp -f ~/$tmpdir1/settings.json ~/www/$(whoami).$(hostname)/public_html/$tmpdir2/settings.json
                            htpasswd -cbm ~/www/$(whoami).$(hostname -f)/public_html/$tmpdir2/.htpasswd "$(whoami)" "$randompass" > /dev/null 2>&1
                            #
                            if [[ -d ~/.nginx/conf.d/000-default-server.d ]]
                            then
                                echo -e 'location /'"$tmpdir2"' {\n    auth_basic "'"$tmpdir2"'";\n    auth_basic_user_file "'"$HOME"'/www/'$(whoami)'.'$(hostname -f)'/public_html/'"$tmpdir2"'/.htpasswd";\n}' > ~/.nginx/conf.d/000-default-server.d/transdroid_import.conf
                                /usr/sbin/nginx -s reload -c ~/.nginx/nginx.conf > /dev/null 2>&1
                            fi
                            #
                            echo -e 'AuthType Basic\nAuthName "'"$tmpdir2"'"\nAuthUserFile "'"$HOME"'/www/'$(whoami)'.'$(hostname -f)'/public_html/'"$tmpdir2"'/.htpasswd"\nRequire "'$(whoami)'"' > ~/www/$(whoami).$(hostname -f)/public_html/"$tmpdir2"/.htaccess
                            #
                            LD_LIBRARY_PATH=~/.transdroid_import/usr/lib/x86_64-linux-gnu ~/.transdroid_import/usr/bin/qrencode -m 1 -t ANSI256 -o - "$URL"
                            #
                            echo
                            echo -e "\033[33m""Use the QRCode for quick access to the generated settings.json""\e[0m"
                            echo
                            echo "1: Download the generated config file to your phone using the following link"
                            echo
                            echo -e "\033[32m""$URL""\e[0m"
                            echo
                            echo -e "2: Open Transdroid/Transdrone and Go to:" "\033[36m""Settings > System > Export settings""\e[0ms so that the appropriate folder is created."
                            echo
                            echo -e "3: Open Transdroid/Transdrone and Go to:" "\033[36m""Settings > System > Import settings""\e[0m"
                            echo
                            echo "4: You will be told which directory the file is required to be in for import. Copy it there then import it."
                            echo
                            read -ep "After you have downloaded the config file, press ENTER to clean up." useless
                            echo
                            #
                            if [[ ! -z "$tmpdir1" && ! -z "$tmpdir2" ]]
                            then
                                cd && rm -rf $tmpdir1 ~/www/$(whoami).$(hostname)/public_html/$tmpdir2
                                if [[ -d ~/.nginx/conf.d/000-default-server.d ]]
                                then
                                    rm -f ~/.nginx/conf.d/000-default-server.d/transdroid_import.conf
                                    /usr/sbin/nginx -s reload -c ~/.nginx/nginx.conf > /dev/null 2>&1
                                fi
                            else
                                echo "Nothing was removed. Please check manually."
                            fi
                            ;;
                    "4")
                            echo "You chose to quit the script."
                            echo
                            exit
                            ;;
            esac
    done
#
############################
##### User Script End  #####
############################
#
else
    echo -e "You chose to exit after updating the scripts."
    echo
    cd && bash
    exit 1
fi
#
############################
##### Core Script Ends #####
############################
#
